import type { ChainTx, Meter, MeterReport, Neighbourhood, Outage } from "./types";

/**
 * Mock data layer.
 * INTEGRATION NOTE: every export here is the shape a future API / indexer will
 * return. Replace these constants with fetches to the GridWitness backend and
 * HSK Chain event logs — component code reads only through the store in
 * `grid-store.tsx`, so no UI change is required.
 */

export const WALLET_ADDRESS = "0x71A4c3F9bE0d47C2a8B1e6D53d90aC7188E482F9";
export const CHAIN_NAME = "HSK Chain";
export const START_BLOCK = 4_812_004;

export function shortHash(hash: string, lead = 6, tail = 4) {
  return `${hash.slice(0, lead)}...${hash.slice(-tail)}`;
}

/** Deterministic pseudo-hash so SSR and client render identically. */
export function makeHash(seed: string) {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  let out = "0x";
  let n = h >>> 0;
  for (let i = 0; i < 16; i++) {
    n = (Math.imul(n, 1103515245) + 12345) >>> 0;
    out += (n % 16).toString(16);
    out += ((n >> 8) % 16).toString(16);
  }
  return out.slice(0, 42);
}

export const neighbourhoods: Neighbourhood[] = [
  {
    id: "yaba",
    name: "Yaba",
    lga: "Lagos Mainland",
    lat: 6.5095,
    lng: 3.3711,
    state: "conflict",
    meters: 42,
    consensus: 67,
    reliability: 61,
    lastBlock: START_BLOCK - 12,
    txHash: makeHash("yaba-base"),
  },
  {
    id: "ikeja",
    name: "Ikeja GRA",
    lga: "Ikeja",
    lat: 6.5795,
    lng: 3.3486,
    state: "on",
    meters: 58,
    consensus: 96,
    reliability: 84,
    lastBlock: START_BLOCK - 4,
    txHash: makeHash("ikeja-base"),
  },
  {
    id: "surulere",
    name: "Surulere",
    lga: "Surulere",
    lat: 6.4969,
    lng: 3.3481,
    state: "outage",
    meters: 47,
    consensus: 89,
    reliability: 54,
    outageStart: "1:05 PM",
    predictedRestoration: "6:40 PM – 7:25 PM",
    lastBlock: START_BLOCK - 31,
    txHash: makeHash("surulere-base"),
  },
  {
    id: "lekki",
    name: "Lekki Phase 1",
    lga: "Eti-Osa",
    lat: 6.4462,
    lng: 3.4736,
    state: "on",
    meters: 63,
    consensus: 98,
    reliability: 88,
    lastBlock: START_BLOCK - 2,
    txHash: makeHash("lekki-base"),
  },
  {
    id: "gbagada",
    name: "Gbagada",
    lga: "Kosofe",
    lat: 6.5556,
    lng: 3.3892,
    state: "predicted",
    meters: 38,
    consensus: 74,
    reliability: 66,
    predictedRestoration: "Outage likely before 9:00 PM",
    lastBlock: START_BLOCK - 9,
    txHash: makeHash("gbagada-base"),
  },
  {
    id: "apapa",
    name: "Apapa",
    lga: "Apapa",
    lat: 6.4489,
    lng: 3.3595,
    state: "outage",
    meters: 21,
    consensus: 82,
    reliability: 47,
    outageStart: "11:42 AM",
    predictedRestoration: "8:10 PM – 9:00 PM",
    lastBlock: START_BLOCK - 44,
    txHash: makeHash("apapa-base"),
  },
  {
    id: "ojota",
    name: "Ojota",
    lga: "Kosofe",
    lat: 6.5833,
    lng: 3.3833,
    state: "unknown",
    meters: 6,
    consensus: 33,
    reliability: 0,
    lastBlock: START_BLOCK - 120,
    txHash: makeHash("ojota-base"),
  },
];

export const featuredMeterIds = ["GW-YB-001", "GW-YB-002", "GW-YB-003"];

export const meters: Meter[] = [
  {
    id: "GW-YB-001",
    name: "Meter A",
    location: "Yaba",
    status: "off",
    trust: 96,
    lastReport: "2:10 PM",
    totalReports: 1284,
    rewards: 2140,
    online: true,
    owner: "Samuel M.",
    accuracy: 97,
    registeredBlock: START_BLOCK - 8420,
  },
  {
    id: "GW-YB-002",
    name: "Meter B",
    location: "Yaba",
    status: "off",
    trust: 93,
    lastReport: "2:11 PM",
    totalReports: 1102,
    rewards: 1875,
    online: true,
    owner: "Chidinma O.",
    accuracy: 94,
    registeredBlock: START_BLOCK - 8210,
  },
  {
    id: "GW-YB-003",
    name: "Meter C",
    location: "Yaba",
    status: "on",
    trust: 72,
    lastReport: "2:12 PM",
    totalReports: 736,
    rewards: 640,
    online: true,
    owner: "Tunde A.",
    accuracy: 71,
    registeredBlock: START_BLOCK - 5110,
  },
  {
    id: "GW-IK-014",
    name: "Ikeja Node 14",
    location: "Ikeja GRA",
    status: "on",
    trust: 98,
    lastReport: "2:09 PM",
    totalReports: 1610,
    rewards: 2480,
    online: true,
    owner: "Adaeze N.",
    accuracy: 98,
    registeredBlock: START_BLOCK - 9900,
  },
  {
    id: "GW-SU-007",
    name: "Surulere Node 7",
    location: "Surulere",
    status: "off",
    trust: 91,
    lastReport: "1:58 PM",
    totalReports: 1320,
    rewards: 1990,
    online: true,
    owner: "Femi B.",
    accuracy: 92,
    registeredBlock: START_BLOCK - 8800,
  },
  {
    id: "GW-SU-019",
    name: "Surulere Node 19",
    location: "Surulere",
    status: "off",
    trust: 88,
    lastReport: "1:44 PM",
    totalReports: 904,
    rewards: 1240,
    online: true,
    owner: "Grace E.",
    accuracy: 89,
    registeredBlock: START_BLOCK - 6400,
  },
  {
    id: "GW-LK-022",
    name: "Lekki Node 22",
    location: "Lekki Phase 1",
    status: "on",
    trust: 95,
    lastReport: "2:12 PM",
    totalReports: 1455,
    rewards: 2205,
    online: true,
    owner: "Ibrahim K.",
    accuracy: 96,
    registeredBlock: START_BLOCK - 9100,
  },
  {
    id: "GW-GB-005",
    name: "Gbagada Node 5",
    location: "Gbagada",
    status: "on",
    trust: 84,
    lastReport: "2:04 PM",
    totalReports: 812,
    rewards: 1010,
    online: true,
    owner: "Ngozi U.",
    accuracy: 85,
    registeredBlock: START_BLOCK - 5600,
  },
  {
    id: "GW-GB-011",
    name: "Gbagada Node 11",
    location: "Gbagada",
    status: "on",
    trust: 79,
    lastReport: "12:36 PM",
    totalReports: 522,
    rewards: 610,
    online: false,
    owner: "Kelechi D.",
    accuracy: 80,
    registeredBlock: START_BLOCK - 4300,
  },
  {
    id: "GW-AP-003",
    name: "Apapa Node 3",
    location: "Apapa",
    status: "off",
    trust: 90,
    lastReport: "1:51 PM",
    totalReports: 1150,
    rewards: 1720,
    online: true,
    owner: "Bola R.",
    accuracy: 91,
    registeredBlock: START_BLOCK - 7700,
  },
  {
    id: "GW-OJ-002",
    name: "Ojota Node 2",
    location: "Ojota",
    status: "on",
    trust: 58,
    lastReport: "9:20 AM",
    totalReports: 143,
    rewards: 180,
    online: false,
    owner: "Peter I.",
    accuracy: 61,
    registeredBlock: START_BLOCK - 1200,
  },
  {
    id: "GW-IK-031",
    name: "Ikeja Node 31",
    location: "Ikeja GRA",
    status: "on",
    trust: 87,
    lastReport: "2:07 PM",
    totalReports: 998,
    rewards: 1385,
    online: true,
    owner: "Halima S.",
    accuracy: 88,
    registeredBlock: START_BLOCK - 6900,
  },
];

export const outages: Outage[] = [
  {
    id: "OUT-2291",
    area: "Surulere",
    status: "active",
    verified: true,
    startTime: "1:05 PM",
    durationMinutes: 187,
    reports: 24,
    consensus: 89,
    prediction: "Power may return between 6:40 PM and 7:25 PM",
    confidence: 74,
    txHash: makeHash("out-2291"),
    block: START_BLOCK - 31,
  },
  {
    id: "OUT-2288",
    area: "Apapa",
    status: "active",
    verified: true,
    startTime: "11:42 AM",
    durationMinutes: 270,
    reports: 14,
    consensus: 82,
    prediction: "Power may return between 8:10 PM and 9:00 PM",
    confidence: 63,
    txHash: makeHash("out-2288"),
    block: START_BLOCK - 44,
  },
  {
    id: "OUT-2286",
    area: "Gbagada",
    status: "pending",
    verified: false,
    startTime: "2:02 PM",
    durationMinutes: 26,
    reports: 9,
    consensus: 44,
    prediction: "Awaiting neighbourhood consensus before an estimate is issued",
    confidence: 38,
    txHash: makeHash("out-2286"),
    block: START_BLOCK - 9,
  },
  {
    id: "OUT-2280",
    area: "Ikeja GRA",
    status: "restored",
    verified: true,
    startTime: "6:14 AM",
    durationMinutes: 142,
    reports: 31,
    consensus: 94,
    prediction: "Restored at 8:36 AM — estimate was accurate within 11 minutes",
    confidence: 91,
    txHash: makeHash("out-2280"),
    block: START_BLOCK - 302,
  },
  {
    id: "OUT-2277",
    area: "Lekki Phase 1",
    status: "restored",
    verified: true,
    startTime: "Yesterday, 7:48 PM",
    durationMinutes: 96,
    reports: 27,
    consensus: 92,
    prediction: "Restored at 9:24 PM — estimate was accurate within 6 minutes",
    confidence: 88,
    txHash: makeHash("out-2277"),
    block: START_BLOCK - 1180,
  },
  {
    id: "OUT-2271",
    area: "Yaba",
    status: "restored",
    verified: true,
    startTime: "Yesterday, 10:12 AM",
    durationMinutes: 214,
    reports: 22,
    consensus: 86,
    prediction: "Restored at 1:46 PM — estimate was accurate within 19 minutes",
    confidence: 79,
    txHash: makeHash("out-2271"),
    block: START_BLOCK - 2410,
  },
];

export const recentReports: MeterReport[] = [
  {
    id: "r1",
    meterId: "GW-LK-022",
    meterName: "Lekki Node 22",
    location: "Lekki Phase 1",
    status: "on",
    time: "2:12 PM",
  },
  {
    id: "r2",
    meterId: "GW-YB-003",
    meterName: "Meter C",
    location: "Yaba",
    status: "on",
    time: "2:12 PM",
  },
  {
    id: "r3",
    meterId: "GW-YB-002",
    meterName: "Meter B",
    location: "Yaba",
    status: "off",
    time: "2:11 PM",
  },
  {
    id: "r4",
    meterId: "GW-YB-001",
    meterName: "Meter A",
    location: "Yaba",
    status: "off",
    time: "2:10 PM",
  },
  {
    id: "r5",
    meterId: "GW-IK-014",
    meterName: "Ikeja Node 14",
    location: "Ikeja GRA",
    status: "on",
    time: "2:09 PM",
  },
  {
    id: "r6",
    meterId: "GW-SU-007",
    meterName: "Surulere Node 7",
    location: "Surulere",
    status: "off",
    time: "1:58 PM",
  },
];

export const initialTransactions: ChainTx[] = [
  {
    id: "tx1",
    kind: "outage_verified",
    label: "Outage verified",
    detail: "Surulere — 89% consensus from 24 meters",
    hash: makeHash("tx-out-surulere"),
    block: START_BLOCK - 31,
    timestamp: "1:07 PM",
  },
  {
    id: "tx2",
    kind: "reward_issued",
    label: "Reward issued",
    detail: "180 GRID distributed to 12 Surulere meters",
    hash: makeHash("tx-reward-surulere"),
    block: START_BLOCK - 30,
    timestamp: "1:08 PM",
  },
  {
    id: "tx3",
    kind: "report_submitted",
    label: "Report submitted",
    detail: "Meter A (GW-YB-001) reported Power OFF in Yaba",
    hash: makeHash("tx-report-a"),
    block: START_BLOCK - 12,
    timestamp: "2:10 PM",
  },
  {
    id: "tx4",
    kind: "consensus_reached",
    label: "Consensus reached",
    detail: "Apapa — 82% agreement across 14 meters",
    hash: makeHash("tx-consensus-apapa"),
    block: START_BLOCK - 44,
    timestamp: "11:46 AM",
  },
  {
    id: "tx5",
    kind: "meter_registered",
    label: "Meter registered",
    detail: "Ikeja Node 31 (GW-IK-031) joined the network",
    hash: makeHash("tx-register-ik31"),
    block: START_BLOCK - 6900,
    timestamp: "Yesterday",
  },
];

/** Electricity availability across the monitored network, last 24 hours. */
export const availability24h = [
  { time: "15:00", availability: 74, outages: 2 },
  { time: "17:00", availability: 68, outages: 3 },
  { time: "19:00", availability: 52, outages: 5 },
  { time: "21:00", availability: 47, outages: 6 },
  { time: "23:00", availability: 55, outages: 5 },
  { time: "01:00", availability: 71, outages: 3 },
  { time: "03:00", availability: 82, outages: 2 },
  { time: "05:00", availability: 79, outages: 2 },
  { time: "07:00", availability: 64, outages: 4 },
  { time: "09:00", availability: 70, outages: 3 },
  { time: "11:00", availability: 66, outages: 4 },
  { time: "13:00", availability: 61, outages: 4 },
  { time: "14:00", availability: 58, outages: 3 },
];

export const outageFrequency = [
  { area: "Yaba", thisWeek: 13, lastWeek: 11 },
  { area: "Ikeja GRA", thisWeek: 5, lastWeek: 8 },
  { area: "Surulere", thisWeek: 12, lastWeek: 12 },
  { area: "Lekki", thisWeek: 4, lastWeek: 5 },
  { area: "Gbagada", thisWeek: 9, lastWeek: 7 },
  { area: "Apapa", thisWeek: 15, lastWeek: 14 },
];

export const averageDuration = [
  { area: "Yaba", hours: 3.4 },
  { area: "Ikeja GRA", hours: 1.8 },
  { area: "Surulere", hours: 4.1 },
  { area: "Lekki", hours: 1.4 },
  { area: "Gbagada", hours: 2.7 },
  { area: "Apapa", hours: 5.2 },
];

export const reliabilityRanking = [
  { area: "Lekki Phase 1", reliability: 88, change: 3 },
  { area: "Ikeja GRA", reliability: 84, change: 9 },
  { area: "Gbagada", reliability: 66, change: -2 },
  { area: "Yaba", reliability: 61, change: -18 },
  { area: "Surulere", reliability: 54, change: -4 },
  { area: "Apapa", reliability: 47, change: 1 },
];

export const trustHistory = [
  { day: "Mon", trust: 91 },
  { day: "Tue", trust: 92 },
  { day: "Wed", trust: 93 },
  { day: "Thu", trust: 94 },
  { day: "Fri", trust: 95 },
  { day: "Sat", trust: 95 },
  { day: "Sun", trust: 96 },
];

export const leaderboard = [
  { owner: "Adaeze N.", meter: "GW-IK-014", location: "Ikeja GRA", accurate: 1578, rewards: 2480 },
  {
    owner: "Ibrahim K.",
    meter: "GW-LK-022",
    location: "Lekki Phase 1",
    accurate: 1397,
    rewards: 2205,
  },
  { owner: "Samuel M.", meter: "GW-YB-001", location: "Yaba", accurate: 1245, rewards: 2140 },
  { owner: "Femi B.", meter: "GW-SU-007", location: "Surulere", accurate: 1214, rewards: 1990 },
  { owner: "Chidinma O.", meter: "GW-YB-002", location: "Yaba", accurate: 1035, rewards: 1875 },
  { owner: "Bola R.", meter: "GW-AP-003", location: "Apapa", accurate: 1046, rewards: 1720 },
  { owner: "Halima S.", meter: "GW-IK-031", location: "Ikeja GRA", accurate: 878, rewards: 1385 },
  { owner: "Grace E.", meter: "GW-SU-019", location: "Surulere", accurate: 804, rewards: 1240 },
];

export const aiInsights = [
  {
    id: "ai1",
    tone: "warning" as const,
    title: "Yaba outage frequency is rising",
    body: "Yaba has experienced 18% more outages this week than last week, concentrated between 6 PM and 10 PM.",
    tag: "Pattern",
  },
  {
    id: "ai2",
    tone: "danger" as const,
    title: "Conflicting report detected",
    body: "Meter GW-YB-003 submitted a report that conflicts with nearby devices. Its trust score has been reduced pending review.",
    tag: "Integrity",
  },
  {
    id: "ai3",
    tone: "success" as const,
    title: "Ikeja reliability improving",
    body: "Ikeja's electricity reliability improved by 9% over the last seven days, with shorter average interruptions.",
    tag: "Reliability",
  },
  {
    id: "ai4",
    tone: "info" as const,
    title: "Possible Surulere outage ahead",
    body: "A possible outage is predicted in Surulere within the next two hours based on load patterns and neighbouring feeder behaviour.",
    tag: "Prediction",
  },
];

export const hotspots = [
  { area: "Surulere", risk: 78, window: "Next 2 hours" },
  { area: "Apapa", risk: 71, window: "Next 3 hours" },
  { area: "Yaba", risk: 64, window: "This evening" },
  { area: "Gbagada", risk: 52, window: "Before 9:00 PM" },
];

export const suspiciousMeters = [
  {
    meterId: "GW-YB-003",
    name: "Meter C",
    reason: "Reported Power ON while 2 nearby meters reported Power OFF",
    severity: "High" as const,
    trustChange: -8,
  },
  {
    meterId: "GW-OJ-002",
    name: "Ojota Node 2",
    reason: "Long reporting gaps and low neighbourhood agreement",
    severity: "Medium" as const,
    trustChange: -4,
  },
  {
    meterId: "GW-GB-011",
    name: "Gbagada Node 11",
    reason: "Offline during two verified neighbourhood outages",
    severity: "Low" as const,
    trustChange: -2,
  },
];
